-- Insert dummy leads into new_patient_leads table
INSERT INTO new_patient_leads (
  personal_first_name,
  personal_last_name,
  personal_phone,
  personal_email,
  first_name,
  last_name,
  date_of_birth,
  gender,
  best_contact_time,
  phone_call_preference,
  preferred_contact,
  best_time_to_call,
  home_address,
  street_address,
  city,
  state,
  zip_code,
  address,
  reason_for_visit,
  dental_problems,
  immediate_needs,
  implant_type,
  urgency,
  need_loved_one_help,
  use_financing,
  credit_score,
  barriers,
  medical_conditions,
  has_medical_insurance,
  hear_about_us,
  additional_notes,
  agree_to_terms,
  status
) VALUES 
-- Lead 1: Sarah Johnson
(
  'Sarah',
  'Johnson',
  '+1 (555) 123-4567',
  'sarah.johnson@email.com',
  'Sarah',
  'Johnson',
  '1985-03-15',
  'female',
  'Morning (9 AM - 12 PM)',
  'Text first, then call',
  'phone',
  'Morning (9 AM - 12 PM)',
  '123 Oak Street',
  '123 Oak Street',
  'Springfield',
  'IL',
  '62701',
  '123 Oak Street, Springfield, IL 62701',
  'Need dental implants for missing teeth',
  ARRAY['Missing teeth', 'Gum disease'],
  ARRAY['Pain relief', 'Cosmetic improvement'],
  'Single tooth implant',
  'medium',
  'no',
  'yes',
  '700-750',
  ARRAY['Cost concerns'],
  ARRAY['Diabetes', 'High blood pressure'],
  'yes',
  'Google search',
  'Very interested in getting implants soon. Has been missing teeth for 2 years.',
  true,
  'new'
),

-- Lead 2: Michael Chen
(
  'Michael',
  'Chen',
  '+1 (555) 234-5678',
  'michael.chen@email.com',
  'Michael',
  'Chen',
  '1978-07-22',
  'male',
  'Evening (5 PM - 8 PM)',
  'Call anytime',
  'email',
  'Evening (5 PM - 8 PM)',
  '456 Pine Avenue',
  '456 Pine Avenue',
  'Chicago',
  'IL',
  '60601',
  '456 Pine Avenue, Chicago, IL 60601',
  'Full mouth reconstruction needed',
  ARRAY['Multiple missing teeth', 'Broken teeth', 'Tooth decay'],
  ARRAY['Full mouth restoration', 'Pain relief'],
  'All-on-4 implants',
  'high',
  'yes',
  'yes',
  '650-700',
  ARRAY['Insurance coverage', 'Time off work'],
  ARRAY['None'],
  'yes',
  'Referral from friend',
  'Needs extensive work. Very motivated to get treatment.',
  true,
  'attempt1'
),

-- Lead 3: Emily Rodriguez
(
  'Emily',
  'Rodriguez',
  '+1 (555) 345-6789',
  'emily.rodriguez@email.com',
  'Emily',
  'Rodriguez',
  '1992-11-08',
  'female',
  'Afternoon (1 PM - 5 PM)',
  'Text preferred',
  'text',
  'Afternoon (1 PM - 5 PM)',
  '789 Maple Drive',
  '789 Maple Drive',
  'Aurora',
  'IL',
  '60502',
  '789 Maple Drive, Aurora, IL 60502',
  'Replace old dental work with implants',
  ARRAY['Old crowns failing', 'Tooth sensitivity'],
  ARRAY['Replace old work', 'Improve appearance'],
  'Multiple implants',
  'low',
  'no',
  'maybe',
  '750-800',
  ARRAY['Cost concerns', 'Recovery time'],
  ARRAY['Anxiety about dental procedures'],
  'no',
  'Facebook ad',
  'Young professional, concerned about appearance and wants modern solution.',
  true,
  'attempt2'
),

-- Lead 4: Robert Williams
(
  'Robert',
  'Williams',
  '+1 (555) 456-7890',
  'robert.williams@email.com',
  'Robert',
  'Williams',
  '1965-05-30',
  'male',
  'Morning (9 AM - 12 PM)',
  'Call preferred',
  'phone',
  'Morning (9 AM - 12 PM)',
  '321 Elm Street',
  '321 Elm Street',
  'Naperville',
  'IL',
  '60540',
  '321 Elm Street, Naperville, IL 60540',
  'Dentures are uncomfortable, want implants',
  ARRAY['Loose dentures', 'Difficulty eating'],
  ARRAY['Stable teeth', 'Better chewing'],
  'Implant-supported dentures',
  'medium',
  'yes',
  'no',
  '600-650',
  ARRAY['Fixed income', 'Age concerns'],
  ARRAY['Heart condition', 'Arthritis'],
  'yes',
  'TV commercial',
  'Retired, on fixed income but very interested in improving quality of life.',
  true,
  'attempt3'
),

-- Lead 5: Jessica Taylor
(
  'Jessica',
  'Taylor',
  '+1 (555) 567-8901',
  'jessica.taylor@email.com',
  'Jessica',
  'Taylor',
  '1988-12-03',
  'female',
  'Evening (6 PM - 9 PM)',
  'Text first',
  'text',
  'Evening (6 PM - 9 PM)',
  '654 Cedar Lane',
  '654 Cedar Lane',
  'Rockford',
  'IL',
  '61101',
  '654 Cedar Lane, Rockford, IL 61101',
  'Accident damaged front teeth',
  ARRAY['Broken front teeth', 'Chipped teeth'],
  ARRAY['Cosmetic repair', 'Confidence boost'],
  'Front tooth implants',
  'high',
  'no',
  'yes',
  '700-750',
  ARRAY['Time constraints'],
  ARRAY['None'],
  'yes',
  'Instagram ad',
  'Recent accident, needs quick solution for front teeth. Very motivated.',
  true,
  'scheduled'
),

-- Lead 6: David Brown
(
  'David',
  'Brown',
  '+1 (555) 678-9012',
  'david.brown@email.com',
  'David',
  'Brown',
  '1975-09-18',
  'male',
  'Lunch time (12 PM - 1 PM)',
  'Email preferred',
  'email',
  'Lunch time (12 PM - 1 PM)',
  '987 Birch Road',
  '987 Birch Road',
  'Peoria',
  'IL',
  '61602',
  '987 Birch Road, Peoria, IL 61602',
  'Considering implants vs bridges',
  ARRAY['Missing back teeth', 'Difficulty chewing'],
  ARRAY['Better chewing', 'Long-term solution'],
  'Posterior implants',
  'low',
  'maybe',
  'maybe',
  '650-700',
  ARRAY['Decision between options', 'Cost comparison'],
  ARRAY['High blood pressure'],
  'yes',
  'Dentist referral',
  'Taking time to research options. Wants to make informed decision.',
  true,
  'new'
),

-- Lead 7: Amanda Davis
(
  'Amanda',
  'Davis',
  '+1 (555) 789-0123',
  'amanda.davis@email.com',
  'Amanda',
  'Davis',
  '1990-04-25',
  'female',
  'Morning (10 AM - 12 PM)',
  'Call anytime',
  'phone',
  'Morning (10 AM - 12 PM)',
  '147 Willow Street',
  '147 Willow Street',
  'Joliet',
  'IL',
  '60431',
  '147 Willow Street, Joliet, IL 60431',
  'Genetic tooth problems, need implants',
  ARRAY['Weak enamel', 'Multiple cavities', 'Tooth loss'],
  ARRAY['Prevent further loss', 'Improve oral health'],
  'Multiple implants',
  'medium',
  'yes',
  'yes',
  '750-800',
  ARRAY['Young age concerns'],
  ARRAY['Genetic dental issues'],
  'yes',
  'Online research',
  'Young mother with genetic dental issues. Wants to prevent passing problems to children.',
  true,
  'attempt1'
),

-- Lead 8: Christopher Wilson
(
  'Christopher',
  'Wilson',
  '+1 (555) 890-1234',
  'chris.wilson@email.com',
  'Christopher',
  'Wilson',
  '1982-08-14',
  'male',
  'Evening (7 PM - 9 PM)',
  'Text preferred',
  'text',
  'Evening (7 PM - 9 PM)',
  '258 Spruce Avenue',
  '258 Spruce Avenue',
  'Elgin',
  'IL',
  '60120',
  '258 Spruce Avenue, Elgin, IL 60120',
  'Sports injury damaged teeth',
  ARRAY['Knocked out teeth', 'Jaw pain'],
  ARRAY['Replace missing teeth', 'Pain relief'],
  'Immediate implants',
  'high',
  'no',
  'yes',
  '700-750',
  ARRAY['Recovery time', 'Sports activities'],
  ARRAY['Previous jaw injury'],
  'yes',
  'Sports medicine referral',
  'Active athlete, needs quick recovery and durable solution.',
  true,
  'scheduled'
),

-- Lead 9: Lisa Anderson
(
  'Lisa',
  'Anderson',
  '+1 (555) 901-2345',
  'lisa.anderson@email.com',
  'Lisa',
  'Anderson',
  '1970-01-12',
  'female',
  'Afternoon (2 PM - 4 PM)',
  'Call preferred',
  'phone',
  'Afternoon (2 PM - 4 PM)',
  '369 Poplar Street',
  '369 Poplar Street',
  'Waukegan',
  'IL',
  '60085',
  '369 Poplar Street, Waukegan, IL 60085',
  'Periodontal disease led to tooth loss',
  ARRAY['Gum disease', 'Loose teeth', 'Tooth loss'],
  ARRAY['Gum health', 'Stable teeth'],
  'All-on-6 implants',
  'medium',
  'yes',
  'no',
  '600-650',
  ARRAY['Gum health concerns', 'Cost'],
  ARRAY['Diabetes', 'Periodontal disease'],
  'yes',
  'Periodontist referral',
  'Has been dealing with gum disease for years. Ready for permanent solution.',
  true,
  'attempt2'
),

-- Lead 10: Mark Thompson
(
  'Mark',
  'Thompson',
  '+1 (555) 012-3456',
  'mark.thompson@email.com',
  'Mark',
  'Thompson',
  '1995-06-20',
  'male',
  'Evening (8 PM - 10 PM)',
  'Text only',
  'text',
  'Evening (8 PM - 10 PM)',
  '741 Hickory Drive',
  '741 Hickory Drive',
  'Schaumburg',
  'IL',
  '60173',
  '741 Hickory Drive, Schaumburg, IL 60173',
  'Congenitally missing teeth',
  ARRAY['Missing lateral incisors', 'Spacing issues'],
  ARRAY['Complete smile', 'Confidence'],
  'Lateral incisor implants',
  'low',
  'no',
  'yes',
  '750-800',
  ARRAY['Age and career concerns'],
  ARRAY['None'],
  'yes',
  'Orthodontist referral',
  'Young professional, born without lateral incisors. Wants complete smile.',
  true,
  'new'
);

-- Update created_at timestamps to have variety
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '1 day' WHERE personal_first_name = 'Sarah';
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '3 days' WHERE personal_first_name = 'Michael';
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '5 days' WHERE personal_first_name = 'Emily';
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '7 days' WHERE personal_first_name = 'Robert';
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '2 days' WHERE personal_first_name = 'Jessica';
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '4 days' WHERE personal_first_name = 'David';
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '6 days' WHERE personal_first_name = 'Amanda';
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '1 day' WHERE personal_first_name = 'Christopher';
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '8 days' WHERE personal_first_name = 'Lisa';
UPDATE new_patient_leads SET created_at = NOW() - INTERVAL '2 hours' WHERE personal_first_name = 'Mark';
